import { Document, Types } from 'mongoose';
import { UserRole } from '../users/user.types.js';

export enum AuditEventType {
  CASE_CREATED = 'CASE_CREATED',
  CASE_UPDATED = 'CASE_UPDATED',
  REPORT_UPLOADED = 'REPORT_UPLOADED',
  REPORT_PROCESSED = 'REPORT_PROCESSED',
  REPORT_OCR_STARTED = 'REPORT_OCR_STARTED',
  REPORT_OCR_PROCESSED = 'REPORT_OCR_PROCESSED',
  REPORT_OCR_FAILED = 'REPORT_OCR_FAILED',
  REPORT_OCR_VERIFIED = 'REPORT_OCR_VERIFIED',
  VISUAL_INPUT_UPLOADED = 'VISUAL_INPUT_UPLOADED',
  VISUAL_ANALYSIS_STARTED = 'VISUAL_ANALYSIS_STARTED',
  VISUAL_ANALYSIS_PROCESSED = 'VISUAL_ANALYSIS_PROCESSED',
  VISUAL_ANALYSIS_FAILED = 'VISUAL_ANALYSIS_FAILED',
  VISUAL_INPUT_VERIFIED = 'VISUAL_INPUT_VERIFIED',
  VOICE_INPUT_UPLOADED = 'VOICE_INPUT_UPLOADED',
  VOICE_TRANSCRIPTION_STARTED = 'VOICE_TRANSCRIPTION_STARTED',
  VOICE_TRANSCRIPTION_PROCESSED = 'VOICE_TRANSCRIPTION_PROCESSED',
  VOICE_TRANSCRIPTION_FAILED = 'VOICE_TRANSCRIPTION_FAILED',
  VOICE_INPUT_VERIFIED = 'VOICE_INPUT_VERIFIED',
  TRANSLATION_REQUESTED = 'TRANSLATION_REQUESTED',
  TRANSLATION_STARTED = 'TRANSLATION_STARTED',
  TRANSLATION_COMPLETED = 'TRANSLATION_COMPLETED',
  TRANSLATION_FAILED = 'TRANSLATION_FAILED',
  TRANSLATION_VERIFIED = 'TRANSLATION_VERIFIED',
  AI_OUTPUT_GENERATED = 'AI_OUTPUT_GENERATED',
  AI_EXTRACTION_REQUESTED = 'AI_EXTRACTION_REQUESTED',
  AI_EXTRACTION_FAILED = 'AI_EXTRACTION_FAILED',
  TIMELINE_GENERATED = 'TIMELINE_GENERATED',
  TIMELINE_GENERATION_FAILED = 'TIMELINE_GENERATION_FAILED',
  MISSING_INFORMATION_GENERATED = 'MISSING_INFORMATION_GENERATED',
  MISSING_INFORMATION_GENERATION_FAILED = 'MISSING_INFORMATION_GENERATION_FAILED',
  SAFETY_FLAG_CREATED = 'SAFETY_FLAG_CREATED',
  REVIEW_STARTED = 'REVIEW_STARTED',
  PRIORITY_CHANGED = 'PRIORITY_CHANGED',
  CASE_ESCALATED = 'CASE_ESCALATED',
  CASE_REFERRED = 'CASE_REFERRED',
  CASE_RESOLVED = 'CASE_RESOLVED',
  CONSENT_RECORDED = 'CONSENT_RECORDED',
  DATA_PURGED = 'DATA_PURGED',
  CASE_CLAIMED = 'CASE_CLAIMED',
  CASE_RELEASED = 'CASE_RELEASED',
  CASE_ASSIGNED = 'CASE_ASSIGNED',
  CASE_UNASSIGNED = 'CASE_UNASSIGNED',
  CASE_SLA_ESCALATED = 'CASE_SLA_ESCALATED',
  SAFETY_EVALUATION_COMPLETED = 'SAFETY_EVALUATION_COMPLETED',
  SAFETY_EVALUATION_FAILED = 'SAFETY_EVALUATION_FAILED',
  SAFETY_FALLBACK_PERSISTENCE_FAILED = 'SAFETY_FALLBACK_PERSISTENCE_FAILED',
  TRIAGE_NOTE_GENERATED = 'TRIAGE_NOTE_GENERATED',
  TRIAGE_NOTE_REGENERATED = 'TRIAGE_NOTE_REGENERATED',
  TRIAGE_NOTE_VERIFIED = 'TRIAGE_NOTE_VERIFIED',
  TRIAGE_NOTE_GENERATION_FAILED = 'TRIAGE_NOTE_GENERATION_FAILED',
}

export type AuditActorRole = UserRole | 'SYSTEM';

export interface IAuditLog {
  _id?: Types.ObjectId;
  actorId: string;
  actorRole: AuditActorRole;
  action: AuditEventType;
  resourceType: string;
  resourceId: string;
  caseId?: Types.ObjectId;
  requestId?: string;
  timestamp: Date;
  source: string;
  outcome: 'SUCCESS' | 'FAILURE';
  metadata?: Record<string, unknown>;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface IAuditLogDocument extends IAuditLog, Document {
  _id: Types.ObjectId;
}
